#!/usr/bin/env bash

# Lock screen with slock after ten mins of inactivity
xautolock -time 10 -locker slock &

./fix-trackpad

# synclient MaxTapTime=0
# synclient MaxTapMove=0
# synclient MaxDoubleTapTime=0
# synclient SingleTapTimeout=0
# synclient PalmDetect=1
# synclient TapAndDragGesture=0
# synclient HorizTwoFingerScroll=1
# synclient RTCornerButton=0
# synclient RBCornerButton=0
# synclient LTCornerButton=0
# synclient LBCornerButton=0
# synclient TapButton1=0
# synclient TapButton2=0
# synclient TapButton3=0
#
# echo "Touchpad settings set"

xrandr --newmode "1440x2560"  318.00  1440 1568 1720 2000  2560 2563 2573 2651 -hsync +vsync

NUM_TIMES_ROTATE_SCREEN=$1

for (( NUM = 0; NUM < "${NUM_TIMES_ROTATE_SCREEN}"; NUM++ ))
do
    # Rotate screen on the right (HDMI-1)
    # HDMI-1 or DP-2-1 is vertical (monitor on the right)
    # screen2="HDMI-1"
    screen2="DP-2-1"
    screen1="eDP-1"

    alt2="left" # this rotates CCW
    xrandr --output $screen1 --primary
    # xrandr --addmode HDMI-1 1440x2560
    # xrandr --output $screen2 --mode 2048x1080 --rotate $alt2 --right-of $screen1  # this is for HDMI-1
    xrandr --output $screen2 --mode 2560x1440 --rotate $alt2 --right-of $screen1
    xrandr --output $screen2 --pos 1920x-1280
done

dropbox start && echo "Started Dropbox service"

redshift &
echo "Started redshift"
