#!/usr/bin/env bash

# Lock screen with slock after ten mins of inactivity
xautolock -time 10 -locker slock &

fix-trackpad

# synclient MaxTapTime=0
# synclient MaxTapMove=0
# synclient MaxDoubleTapTime=0
# synclient SingleTapTimeout=0
# synclient PalmDetect=1
# synclient TapAndDragGesture=0
# synclient HorizTwoFingerScroll=1
# synclient RTCornerButton=0
# synclient RBCornerButton=0
# synclient LTCornerButton=0
# synclient LBCornerButton=0
# synclient TapButton1=0
# synclient TapButton2=0
# synclient TapButton3=0
#
# echo "Touchpad settings set"

# The following is from the output of
# cvt 2560 1440
## 2560x1440 59.96 Hz (CVT 3.69M9) hsync: 89.52 kHz; pclk: 312.25 MHz
# Modeline "2560x1440_60.00"  312.25  2560 2752 3024 3488  1440 1443 1448 1493 -hsync +vsync
# The newmode command will probably error if the mode already exists, which it 
# (I think) should
xrandr --newmode "2560x1440" 312.25  2560 2752 3024 3488  1440 1443 1448 1493 -hsync +vsync
xrandr --addmode "DP-2-1" "2560x1440"

# NOTE: For a GUI to help get the screen layout set, install and use arandr,
# and save the profile to generate a script with the corresponding xrandr
# command instead of cobbling it together manually as I have attempted to do in
# the past

# Running arandr-generated xrandr script
preferred-w-docking-station

dropbox start && echo "Started Dropbox service"

redshift &
echo "Started redshift"
